services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_KEY
        value: base64:ZeOruQBqgJHUJ/o8IuC3R3FpuJ77sT/Qg3blOzFkOu8=
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-us-east-2.pooler.supabase.com
      - key: DB_PORT
        value: 6543
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.lyxhceqquioucmlmhvuj
      - key: DB_PASSWORD
        value: nqC5SFwkQulXRnEW
